const COURSE_CONFIG = {
  title: 'Microprocessor A–Z',
  subtitle: 'Master 8086, assembly, interrupts, and interfacing in <strong>48 lessons</strong>',
  shortTitle: 'Microprocessor A–Z',
  org: 'Teamz Lab',
  orgUrl: 'https://teamzlab.com',
  orgFull: 'Teamz Lab LTD',
  siteUrl: 'https://learn.teamzlab.com/',
  canonicalUrl: 'https://learn.teamzlab.com/learn.html?course=microprocessor-a-z',
  ogImage: 'https://learn.teamzlab.com/og-microprocessor.png',
  description: 'Free interactive microprocessor course with {lessonCount} lessons covering 8086 architecture, assembly language, addressing modes, interrupts, memory and I/O interfacing, peripheral chips, and modern processor foundations — no signup required.',
  keywords: 'free microprocessor course, microprocessor tutorial for beginners, 8086 microprocessor course free, learn 8086 assembly language, microprocessor and interfacing course, microprocessor vs microcontroller explained, 8086 architecture explained simply, 8086 registers explained, segmented memory in 8086, physical address calculation in 8086, 8086 addressing modes tutorial, 8086 instruction set for beginners, 8086 assembly programming examples, assembly language programming for 8086, flags register in 8086, jumps and loops in 8086, stack in 8086 explained, interrupts in 8086 explained, dos bios interrupts 8086, memory interfacing with 8086, io interfacing with 8086, 8255 interfacing tutorial, 8259 interrupt controller tutorial, 8237 dma controller explained, 8251 serial communication tutorial, minimum mode and maximum mode 8086, bus timing diagram 8086, machine cycle and t state 8086, microprocessor notes for engineering students, microprocessor viva questions, microprocessor interview questions, microprocessor solved problems, learn microprocessor from zero, free interactive 8086 course, microprocessor roadmap for students, microprocessor course no signup, microprocessor course with quiz, microprocessor projects for students, x86 basics for beginners, embedded systems microprocessor foundation',
  topics: [
    'Foundations',
    'Core Processor Model',
    '8086 Architecture',
    'Pins, Signals, and Modes',
    'Addressing and Data Representation',
    'Instruction Set Essentials',
    'Control Flow and Structured Assembly',
    'Assembly Programming Practice',
    'Stack and Interrupts',
    'Interfacing Fundamentals',
    'Timers, DMA, and Serial Communication',
    'Modern Bridge and Capstone'
  ],
  educationalLevel: 'Beginner to Advanced',
  footerTagline: 'Learn the machine beneath the software.',
  thinkDeeperQ: 'Imagine you\'re designing an embedded system (like a traffic light controller or a washing machine). Why would you need <strong>{title}</strong>? What would fail WITHOUT it?',
  topicMap: {
    'Foundations': [1, 2, 3, 4],
    'Core Processor Model': [5, 6, 7, 8],
    '8086 Architecture': [9, 10, 11, 12],
    'Pins, Signals, and Modes': [13, 14, 15, 16],
    'Addressing and Data Representation': [17, 18, 19, 20],
    'Instruction Set Essentials': [21, 22, 23, 24],
    'Control Flow and Structured Assembly': [25, 26, 27, 28],
    'Assembly Programming Practice': [29, 30, 31, 32],
    'Stack and Interrupts': [33, 34, 35, 36],
    'Interfacing Fundamentals': [37, 38, 39, 40],
    'Timers, DMA, and Serial Communication': [41, 42, 43, 44],
    'Modern Bridge and Capstone': [45, 46, 47, 48]
  },
  conceptFlows: {
    1: ['Problem to solve', 'CPU on a chip', 'Reads instructions', 'Produces action/output'],
    2: ['General-purpose compute', 'Dedicated control', 'External vs integrated parts', 'Choose the right device'],
    3: ['Bits form patterns', 'Bases represent values', 'Hex shortens binary', 'Engineers read memory faster'],
    4: ['AND/OR/NOT', 'Adder logic', 'State changes with clock', 'Logic builds processors'],
    5: ['Fetch instruction', 'Decode meaning', 'Execute operation', 'Repeat millions of times'],
    6: ['Store in registers', 'Compute in ALU', 'Control signals coordinate', 'Buses move data'],
    7: ['Clock ticks', 'T-states combine', 'Machine cycles form work', 'Timing controls hardware'],
    8: ['Program lives in memory', 'CPU addresses location', 'Reads/writes data', 'I/O extends capability'],
    9: ['Why 8086 mattered', '16-bit design', 'x86 lineage begins', 'Still great for fundamentals'],
    10: ['BIU fetches bytes', 'Queue stores ahead', 'EU executes instructions', 'Overlap boosts speed'],
    11: ['General registers', 'Pointer/index registers', 'Segment registers', 'Flags complete state'],
    12: ['Segment base chosen', 'Offset added', '20-bit address formed', 'Memory location reached'],
    13: ['Pins expose intent', 'Address/data/control roles', 'Read/write signaling', 'External devices coordinate'],
    14: ['Single processor setup', 'Bus controller support', 'Minimum mode flow', 'Maximum mode flow'],
    15: ['Address appears', 'Control lines assert', 'Peripheral responds', 'Wait states stretch timing'],
    16: ['Reset starts clean', 'Hold requests bus', 'HLDA grants control', 'System stabilizes'],
    17: ['Choose operand source', 'Direct or register', 'Indirect or indexed', 'Write shorter faster code'],
    18: ['Byte vs word', 'Little-endian storage', 'Alignment intuition', 'Memory interpretation matters'],
    19: ['Text as ASCII', 'Decimal as BCD', 'Signed value rules', 'Binary meaning changes context'],
    20: ['Base register', 'Index/displacement', 'Compute effective address', 'Trace the final memory access'],
    21: ['Move data safely', 'Load/store patterns', 'Exchange and transfer', 'Memory/register flow'],
    22: ['Add/subtract', 'Multiply/divide basics', 'Carry and borrow', 'Result affects flags'],
    23: ['AND/OR/XOR', 'Compare and test', 'Shift bits', 'Rotate for control/math'],
    24: ['Status gets updated', 'Zero/sign/carry matter', 'Conditions become branches', 'Logic drives decisions'],
    25: ['Sequential flow', 'Branch on condition', 'Loop by counter', 'Programs become dynamic'],
    26: ['Break into procedures', 'CALL saves return', 'RET resumes caller', 'Reuse becomes easier'],
    27: ['Operate on strings', 'Auto index update', 'REP repeats work', 'Bulk memory gets easier'],
    28: ['Assembler directives guide build', 'Labels name locations', 'Macros reduce repetition', 'Programs scale better'],
    29: ['Choose tool', 'Read source format', 'Assemble mentally', 'Debug with confidence'],
    30: ['Write simple instructions', 'Load data', 'Compute result', 'Inspect registers/output'],
    31: ['Traverse arrays', 'Process tables', 'Read memory blocks', 'Structure repeated data'],
    32: ['Single-step execution', 'Watch flags change', 'Inspect memory', 'Find bug root cause'],
    33: ['Stack grows in memory', 'PUSH stores state', 'POP restores state', 'Nested logic becomes possible'],
    34: ['Event occurs', 'Vector identifies handler', 'CPU jumps to ISR', 'Control returns later'],
    35: ['Software INT invoked', 'Hardware line triggers', 'Context is saved', 'Service routine runs'],
    36: ['Use BIOS/DOS calls', 'Pass values in registers', 'Console I/O works', 'Low-level apps feel real'],
    37: ['Address decoding', 'Map ROM/RAM', 'Control read/write', 'System accesses memory correctly'],
    38: ['Separate I/O space', 'Shared memory space', 'Instruction differences', 'Design trade-offs emerge'],
    39: ['Ports grouped', 'Control word configures mode', 'Read/write peripherals', 'Parallel I/O becomes simple'],
    40: ['Input from keyboard', 'Output to LEDs', 'Drive display hardware', 'Full loop of interaction'],
    41: ['Clock source arrives', 'Counter decrements', 'Mode controls behavior', 'Timing events are generated'],
    42: ['Interrupt requests gather', 'Priority decided', 'Vector assigned', 'CPU services cleanly'],
    43: ['Peripheral requests transfer', 'DMA gets bus control', 'Data moves directly', 'CPU overhead drops'],
    44: ['Serial bits framed', 'Transmit and receive paths', 'USART handles timing', 'Device talks over wire'],
    45: ['8086 foundations', 'Protected/32-bit growth', 'Caches and pipelines rise', 'Modern x86 makes sense'],
    46: ['Microprocessor vs MCU roles', '8051 for control', 'ARM for modern systems', 'Shared fundamentals remain'],
    47: ['Pick CPU and memory', 'Choose peripherals', 'Map addresses and signals', 'Validate design choices'],
    48: ['Read full problem', 'Trace execution', 'Explain interfacing', 'Present complete solution']
  },
  srs: { boxes: 5, intervals: [0, 1, 3, 7, 14], reviewBatchSize: 10 },
  xp: {
    lessonComplete: 20,
    quizPerfect: 30,
    challengeComplete: 25,
    bugSolved: 25,
    flashcardMastered: 10,
    reviewComplete: 15
  },
  social: {
    hashtags: '#Microprocessor #8086 #AssemblyLanguage #EmbeddedSystems #TeamzLab',
    tweetTemplate: 'I am learning Microprocessor A–Z for free on Teamz Lab Learning — 8086, assembly, interrupts, interfacing, and more. No signup needed.'
  }
};
