const COURSE_CONFIG = {
  title: 'NU ইনভেস্টমেন্ট ব্যাংকিং ও লিজ ফাইন্যান্স মাস্টারি',
  subtitle: 'A+ প্রস্তুতির জন্য <strong>{lessonCount}টি লেসন</strong>, বাংলাদেশি উদাহরণ, শর্ট নোট, স্মার্ট রিভিশন ও এক্সাম স্ট্র্যাটেজি',
  shortTitle: 'ইনভেস্টমেন্ট ব্যাংকিং',
  org: 'Teamz Lab',
  siteUrl: 'https://learn.teamzlab.com/',
  canonicalUrl: 'https://learn.teamzlab.com/learn.html?course=nu-investment-banking-lease-finance-bn',
  forceLang: 'bn',
  defaultLang: 'bn',
  description: 'NU Masters Finance & Banking-এর Investment Banking and Lease Finance (312401) পেপারের জন্য {lessonCount}টি Bangla lesson, বাংলাদেশি উদাহরণ, শর্ট নোট, compare lessons, valuation basics, lease finance logic ও exam-smart preparation — একদম free, no signup.',
  keywords: 'nu investment banking and lease finance, 312401, national university masters finance and banking, investment banking bangla, lease finance bangla, merchant banking bangla, ipo bangla, underwriting bangla, primary market vs secondary market bangla, bond valuation bangla, equity valuation bangla, finance lease vs operating lease bangla, lease vs loan vs hire purchase bangla, BSEC DSE ICB bangla, Bangladesh capital market course, investment banking and lease finance suggestion, short note, mcq, exam preparation, free course, no signup',
  topics: [
    'ভিত্তি ও কোর্স ওরিয়েন্টেশন',
    'সিকিউরিটিজ মার্কেটের ভিত্তি',
    'প্রাইমারি মার্কেট ও ইস্যু ম্যানেজমেন্ট',
    'মার্চেন্ট ব্যাংকিং ও বাংলাদেশি প্রতিষ্ঠান',
    'সেকেন্ডারি মার্কেট ও বিনিয়োগকারী সুরক্ষা',
    'পোর্টফোলিও, বিশ্লেষণ ও টেকনিক্যাল অ্যানালাইসিস',
    'সিকিউরিটি ভ্যালুয়েশন',
    'লিজ ফাইন্যান্সের ভিত্তি',
    'বাংলাদেশে লিজ ফাইন্যান্স ও সিদ্ধান্ত',
    'A+ রিভিশন ও পরীক্ষার কৌশল'
  ],
  educationalLevel: 'Beginner to Exam Mastery',
  topicMap: {
    'ভিত্তি ও কোর্স ওরিয়েন্টেশন': [1, 2, 3, 4],
    'সিকিউরিটিজ মার্কেটের ভিত্তি': [5, 6, 7, 8, 9],
    'প্রাইমারি মার্কেট ও ইস্যু ম্যানেজমেন্ট': [10, 11, 12, 13, 14, 15],
    'মার্চেন্ট ব্যাংকিং ও বাংলাদেশি প্রতিষ্ঠান': [16, 17, 18, 19, 20],
    'সেকেন্ডারি মার্কেট ও বিনিয়োগকারী সুরক্ষা': [21, 22, 23, 24],
    'পোর্টফোলিও, বিশ্লেষণ ও টেকনিক্যাল অ্যানালাইসিস': [25, 26, 27, 28, 29, 30],
    'সিকিউরিটি ভ্যালুয়েশন': [31, 32, 33, 34],
    'লিজ ফাইন্যান্সের ভিত্তি': [35, 36, 37, 38, 39, 40],
    'বাংলাদেশে লিজ ফাইন্যান্স ও সিদ্ধান্ত': [41, 42, 43],
    'A+ রিভিশন ও পরীক্ষার কৌশল': [44, 45, 46]
  },
  conceptFlows: {
    1: ['পেপার চিনে নাও', 'স্কোরিং জোন ধরো', 'রোডম্যাপ বানাও', 'রিভিশন সিস্টেম সেট করো'],
    2: ['ধারণা', 'ফাংশন', 'বাংলাদেশি scope', 'এক্সাম ভাষা'],
    3: ['তিন প্রতিষ্ঠানের পরিচয়', 'মূল কাজ', 'পার্থক্য', 'মনে রাখার ফ্রেম'],
    4: ['লিজ কী', 'কেন দরকার', 'ব্যবসায় প্রয়োগ', 'পরীক্ষার ভাষা'],
    5: ['ফাইন্যান্সিয়াল মার্কেট', 'ক্যাপিটাল মার্কেট', 'অংশগ্রহণকারী', 'ফ্লো বুঝো'],
    6: ['রিটার্ন', 'রিস্ক', 'trade-off', 'asset allocation'],
    7: ['শেয়ার', 'বন্ড', 'ফান্ড', 'কখন কোনটি'],
    8: ['নতুন ইস্যু', 'পুরনো শেয়ার', 'অংশগ্রহণকারী', 'compare'],
    9: ['BSEC', 'DSE/CSE', 'ICB/CDBL', 'বাংলাদেশি মানচিত্র'],
    10: ['ইস্যু পরিকল্পনা', 'ডকুমেন্টেশন', 'অনুমোদন', 'বাজারে আনা'],
    11: ['প্রসপেক্টাস', 'তথ্য প্রকাশ', 'ঝুঁকি অংশ', 'exam note'],
    12: ['fixed price', 'book building', 'দাম নির্ধারণ', 'বাংলাদেশি প্রয়োগ'],
    13: ['private placement', 'rights issue', 'public issue', 'decision map'],
    14: ['আন্ডাররাইটিং কী', 'ঝুঁকি গ্রহণ', 'প্রকারভেদ', 'গুরুত্ব'],
    15: ['প্রশ্ন ধরো', 'উত্তরের কাঠামো', 'উদাহরণ দাও', 'উচ্চ নম্বর তোল'],
    16: ['মার্চেন্ট ব্যাংকিং', 'সেবা', 'ক্যাপিটাল মার্কেট ভূমিকা', 'exam recall'],
    17: ['issue manager', 'underwriter', 'broker', 'dealer'],
    18: ['regulator', 'exchange', 'institutional investor', 'depository'],
    19: ['investor protection', 'insider trading', 'abuse', 'নিয়ন্ত্রণ'],
    20: ['issuer', 'issue manager', 'BSEC', 'listing journey'],
    21: ['dealer role', 'broker role', 'নিজের বনাম অন্যের জন্য', 'compare'],
    22: ['inventory', 'risk', 'funding', 'control'],
    23: ['abuse types', 'warning signs', 'compliance', 'exam framing'],
    24: ['indicator কী', 'কোন data দেখবে', 'interpretation', 'answer use'],
    25: ['portfolio idea', 'diversification', 'objective', 'manager role'],
    26: ['efficient market', 'pricing intuition', 'assumptions', 'limitations'],
    27: ['statement ধরো', 'ratio পড়ো', 'signal বের করো', 'investment use'],
    28: ['macro factors', 'forecast', 'market link', 'exam answer'],
    29: ['industry view', 'company view', 'strength test', 'decision'],
    30: ['chart idea', 'indicator logic', 'benefit', 'limitations'],
    31: ['valuation process', 'inputs', 'discount idea', 'output'],
    32: ['bond basics', 'coupon', 'yield', 'price relation'],
    33: ['cash flow', 'discounting', 'bond value', 'yield interpretation'],
    34: ['equity logic', 'earnings/dividend', 'simple valuation', 'exam use'],
    35: ['lease concept', 'objectives', 'business need', 'Bangladesh fit'],
    36: ['types of lease', 'features', 'use cases', 'classification'],
    37: ['finance lease', 'operating lease', 'risk transfer', 'compare'],
    38: ['lease', 'term loan', 'hire purchase', 'best choice'],
    39: ['cash flow view', 'lessee logic', 'decision criteria', 'worked example'],
    40: ['advantages', 'limitations', 'accounting/tax', 'balanced answer'],
    41: ['equipment lease', 'sale-and-lease-back', 'cases', 'exam application'],
    42: ['NBFI ecosystem', 'industry examples', 'Bangladesh practice', 'reality check'],
    43: ['wrong choice ধরো', 'cost logic', 'ownership logic', 'right answer'],
    44: ['short note bank', 'one-page memory', 'rapid recall', 'scoring style'],
    45: ['major differences', '2-column answers', 'quick revision', 'exam confidence'],
    46: ['long question plan', 'time management', 'answer sequence', 'final drill']
  },
  srs: {
    boxes: 5,
    intervals: [0, 1, 3, 7, 14],
    reviewBatchSize: 10
  },
  xp: {
    lessonComplete: 20,
    quizPerfect: 30,
    quizPass: 15,
    challengeComplete: 25,
    bugFix: 20,
    flashcardReview: 5,
    streakBonus: 10
  },
  social: {
    hashtags: '#NUBangla #InvestmentBanking #LeaseFinance #MastersExam #TeamzLabLearning',
    tweetTemplate: 'NU ইনভেস্টমেন্ট ব্যাংকিং ও লিজ ফাইন্যান্স মাস্টারি — free Bangla course, no signup, বাংলাদেশি উদাহরণসহ। {url}'
  },
  footerTagline: 'গাইড মুখস্থ না, আসল বোঝাপড়া — তাহলেই উত্তর হবে আত্মবিশ্বাসী।'
};
