const COURSE_CONFIG = {
  title: 'eBook Business Masterclass',
  subtitle: 'Build Your Digital Product Empire — <strong>38 Hands-On Lessons</strong> — Learn to Create, Market & Sell eBooks Online | Free, No Signup | by Teamz Lab',
  shortTitle: 'eBook Business Masterclass',
  org: 'Teamz Lab',
  orgUrl: 'https://github.com/Teamz-Lab-LTD',
  orgFull: 'Teamz Lab LTD',
  siteUrl: 'https://learn.teamzlab.com/',
  canonicalUrl: 'https://learn.teamzlab.com/learn.html?course=ebook-business',
  ogImage: 'https://learn.teamzlab.com/og-ebook-business.png',
  description: 'Free eBook business course: {lessonCount} lessons to create, market & sell digital products. Facebook Ads, funnels, pricing, scaling — no signup required.',
  keywords: 'ebook business course free, how to sell ebooks online, digital product business, create and sell ebooks, ebook marketing strategy, facebook ads for ebooks, sell digital products online, ebook business for beginners, passive income ebooks, self publishing course free, how to write an ebook, ebook cover design, gumroad selling guide, shopify digital products, ebook pricing strategy, email marketing for ebooks, sales funnel digital products, ebook niche research, amazon kdp course free, digital product ideas, online business side income, ebook business plan, content marketing ebooks, seo for digital products, landing page conversion, ebook bundle pricing, affiliate marketing digital products, ebook copyright guide, print on demand ebooks, digital product empire 2026',
  topics: ['Digital Products', 'Market Research', 'Niche Selection', 'eBook Creation', 'Writing', 'Design', 'Editing', 'Distribution', 'E-commerce', 'Payment Gateways', 'Conversion Optimization', 'Pricing Strategy', 'Monetization', 'Branding', 'Content Marketing', 'Email Marketing', 'SEO', 'Facebook Ads', 'Google Ads', 'Social Media Ads', 'Sales Funnels', 'Automation', 'Analytics', 'Scaling', 'Affiliate Marketing', 'Legal'],
  educationalLevel: 'Beginner to Advanced',
  footerTagline: 'Learn to create, market, and sell eBooks & digital products — from first idea to passive income empire.',
  thinkDeeperQ: 'Imagine you\'re launching your eBook business tomorrow. Why would understanding <strong>{title}</strong> be critical to your success? What could go wrong if you skip this step?',
  topicMap: {
    'Getting Started': [1, 2, 3, 4],
    'Finding Your Niche': [5, 6, 7],
    'Creating Your eBook': [8, 9, 10, 11, 12],
    'Building Your Store': [13, 14, 15, 16],
    'Pricing & Monetization': [17, 18, 19],
    'Marketing Foundations': [20, 21, 22, 23],
    'Paid Advertising': [24, 25, 26, 27, 28],
    'Sales Funnels & Automation': [29, 30, 31],
    'Scaling & Advanced': [32, 33, 34, 35, 36],
    'Mastering the Game': [37, 38]
  },
  conceptFlows: {
    1: ['Market Size', 'Growth', 'Opportunity', 'Action'],
    2: ['eBooks', 'Templates', 'Courses', 'Printables'],
    3: ['Mindset', 'Discipline', 'Resilience', 'Growth'],
    4: ['Tools', 'Setup', 'Budget', 'Launch Ready'],
    5: ['Audience', 'Problems', 'Demand', 'Validate'],
    6: ['Keywords', 'Trends', 'Competition', 'Pick Niche'],
    7: ['Demographics', 'Pain Points', 'Desires', 'Avatar'],
    8: ['Topic', 'Outline', 'Structure', 'Plan'],
    9: ['Draft', 'AI Tools', 'Edit', 'Polish'],
    10: ['Cover', 'Layout', 'Typography', 'Professional'],
    11: ['Grammar', 'Style', 'Beta Read', 'Final Check'],
    12: ['PDF', 'EPUB', 'DRM', 'Distribute'],
    13: ['Compare', 'Features', 'Fees', 'Choose'],
    14: ['Domain', 'Design', 'Pages', 'Go Live'],
    15: ['Stripe', 'PayPal', 'Local', 'Multi-Currency'],
    16: ['Headline', 'Copy', 'Proof', 'CTA'],
    17: ['Psychology', 'Anchoring', 'Tiers', 'Optimize'],
    18: ['Bundle', 'Upsell', 'Cross-sell', 'AOV'],
    19: ['Subscription', 'Membership', 'MRR', 'Retain'],
    20: ['Identity', 'Voice', 'Trust', 'Consistency'],
    21: ['Blog', 'YouTube', 'Social', 'Repurpose'],
    22: ['List Build', 'Lead Magnet', 'Nurture', 'Convert'],
    23: ['Keywords', 'On-Page', 'Content', 'Rank'],
    24: ['Pixel', 'Audiences', 'Budget', 'Launch'],
    25: ['Creative', 'Copy', 'Test', 'Optimize'],
    26: ['Retarget', 'Lookalike', 'Scale', 'ROAS'],
    27: ['Search', 'Display', 'YouTube', 'Convert'],
    28: ['TikTok', 'Reels', 'Short-Form', 'Viral'],
    29: ['Awareness', 'Interest', 'Decision', 'Purchase'],
    30: ['Headline', 'Design', 'CTA', 'Convert'],
    31: ['Sequences', 'Triggers', 'Recovery', 'Scale'],
    32: ['Track', 'Measure', 'Analyze', 'Decide'],
    33: ['Expand', 'Diversify', 'Systematize', 'Empire'],
    34: ['Recruit', 'Commission', 'Track', 'Grow'],
    35: ['Localize', 'Currency', 'Tax', 'Global'],
    36: ['Copyright', 'License', 'Tax', 'Protect'],
    37: ['Study', 'Patterns', 'Strategies', 'Apply'],
    38: ['Plan', 'Execute', 'Measure', 'Iterate']
  },
  srs: {
    boxes: 5,
    intervals: [0, 1, 3, 7, 14],
    reviewBatchSize: 10
  },
  xp: {
    lessonComplete: 20,
    quizPerfect: 30,
    quizGood: 20,
    quizOk: 10,
    typingChallenge: 15,
    selfExplanation: 10,
    reviewCorrect: 5,
    mixedQuizComplete: 25
  },
  social: {
    hashtags: 'eBookBusiness,DigitalProducts,PassiveIncome,SellEbooks,OnlineBusiness2026',
    tweetTemplate: 'Just found this FREE eBook Business Masterclass — {lessonCount} interactive lessons to create, market & sell digital products! Quizzes, templates, zero signup.'
  },
  branding: {
    trustStrip: 'We build production-grade web & mobile apps and digital platforms. <strong>This free course is how we give back.</strong>',
    trustStripCta: 'Need a digital product platform? Talk to us',
    headerSubtitle: 'From Idea to Digital Empire — Free, Hands-On eBook Business Training | by',
    ebookUrl: 'https://www.amazon.com/dp/B0GS3GSJ5V',
    ebookTitle: 'Get the Full Book',
    ebookSubtitle: 'Zero to Advanced Web Dev — the complete guide on Amazon',
    footerCtaTitle: 'Need a Custom Digital Product Platform?',
    footerCtaDesc: 'Teamz Lab builds e-commerce platforms, mobile apps, and SaaS products with <strong style="color:var(--heading)">TypeScript, NestJS, React & Flutter</strong>. We built this free course — imagine what we can build for your digital business.',
    services: [
      { name: 'E-commerce Development', desc: 'Custom Shopify, WooCommerce, and headless commerce solutions for digital product sellers' },
      { name: 'Mobile App Development', desc: 'Cross-platform Flutter & React Native apps for iOS and Android' },
      { name: 'SaaS & Platform Development', desc: 'Custom membership platforms, course delivery systems, and creator tools' },
      { name: 'AI Integration & Consulting', desc: 'AI-powered content generation, recommendation engines, and marketing automation' }
    ]
  }
};
