const COURSE_CONFIG = {
  title: 'Clothing Business Masterclass',
  subtitle: 'Build Your Fashion Empire — <strong>30 Hands-On Lessons</strong> — Learn to Start, Run & Scale a Clothing Business | Free, No Signup | by Teamz Lab',
  shortTitle: 'Clothing Business Masterclass',
  org: 'Teamz Lab',
  orgUrl: 'https://github.com/Teamz-Lab-LTD',
  orgFull: 'Teamz Lab LTD',
  siteUrl: 'https://learn.teamzlab.com/',
  canonicalUrl: 'https://learn.teamzlab.com/learn.html?course=clothing-business',
  ogImage: 'https://learn.teamzlab.com/og-clothing-business.png',
  description: 'Free clothing business course: {lessonCount} lessons to start, brand, manufacture & scale a clothing line. Quizzes, templates, checklists — no signup.',
  keywords: 'clothing business course free, how to start a clothing brand, fashion startup guide, clothing line business plan, clothing brand marketing, fashion entrepreneur course, start clothing line from scratch, clothing business for beginners, fashion business plan template, how to manufacture clothes, clothing brand branding guide, fashion e-commerce setup, clothing pricing strategy, clothing inventory management, fashion social media marketing, influencer marketing fashion, clothing wholesale guide, sustainable fashion business, clothing brand scaling, fashion industry course free, how to design clothes, fabric sourcing guide, clothing production guide, fashion photography tips, clothing business financial planning, pop-up shop guide, clothing supply chain, fashion brand identity, clothing business startup cost, fashion retail guide 2026',
  topics: ['Fashion Industry', 'Market Research', 'Business Planning', 'Branding', 'Product Design', 'Fabric Sourcing', 'Manufacturing', 'Pricing Strategy', 'Inventory Management', 'E-commerce', 'Social Media Marketing', 'Paid Advertising', 'Wholesale', 'Retail', 'Supply Chain', 'Sustainability', 'Financial Management', 'Scaling'],
  educationalLevel: 'Beginner to Advanced',
  footerTagline: 'Learn to start, brand, manufacture, market, and scale your clothing business — from first sketch to global brand.',
  thinkDeeperQ: 'Imagine you\'re launching your own clothing brand tomorrow. Why would <strong>{title}</strong> be critical to your success? What could go wrong if you skip this step?',
  topicMap: {
    'Getting Started': [1, 2, 3],
    'Market Research & Niche': [4, 5],
    'Business Planning & Legal': [6, 7],
    'Branding & Identity': [8, 9],
    'Product Design & Development': [10, 11, 12],
    'Manufacturing & Production': [13, 14],
    'Pricing & Finance': [15, 16],
    'Inventory Management': [17],
    'E-commerce & Online Sales': [18, 19, 20],
    'Marketing & Social Media': [21, 22, 23],
    'Sales Channels & Retail': [24, 25],
    'Customer Service': [26],
    'Supply Chain & Logistics': [27],
    'Sustainability & Ethics': [28],
    'Scaling & Growth': [29, 30]
  },
  conceptFlows: {
    1: ['Market Size', 'Segments', 'Trends', 'Opportunity'],
    2: ['Private Label', 'Cut & Sew', 'POD', 'Dropship'],
    3: ['Mindset', 'Resilience', 'Creativity', 'Execution'],
    4: ['Research', 'Personas', 'Competitors', 'Trends'],
    5: ['Niche', 'Position', 'Differentiate', 'Validate'],
    6: ['Plan', 'Finances', 'Operations', 'Funding'],
    7: ['Register', 'Trademark', 'Compliance', 'Protect'],
    8: ['Story', 'Visual Identity', 'Voice', 'Guidelines'],
    9: ['Labels', 'Packaging', 'Unboxing', 'Sustainability'],
    10: ['Mood Board', 'Sketches', 'Tech Pack', 'Collection'],
    11: ['Fabric Types', 'Properties', 'Sourcing', 'Testing'],
    12: ['Pattern', 'Sample', 'Fit Test', 'Production Ready'],
    13: ['Find Factory', 'Evaluate', 'Negotiate', 'Partner'],
    14: ['Timeline', 'Samples', 'QC Inspect', 'Ship'],
    15: ['COGS', 'Markup', 'Margin', 'Breakeven'],
    16: ['Revenue', 'Expenses', 'Cash Flow', 'Profit'],
    17: ['SKUs', 'Track', 'Reorder', 'Warehouse'],
    18: ['Platform', 'Design', 'Products', 'Launch'],
    19: ['Flat Lay', 'On Model', 'Lifestyle', 'Edit'],
    20: ['Product Page', 'Social Proof', 'Cart Recovery', 'Convert'],
    21: ['Instagram', 'TikTok', 'Content', 'Community'],
    22: ['Find', 'Outreach', 'Collaborate', 'Measure ROI'],
    23: ['Facebook Ads', 'Retarget', 'Email', 'ROAS'],
    24: ['Line Sheet', 'Buyers', 'Trade Shows', 'Terms'],
    25: ['Pop-Up', 'Merchandising', 'POS', 'Omnichannel'],
    26: ['Support', 'Returns', 'Feedback', 'Loyalty'],
    27: ['Carriers', 'Rates', '3PL', 'International'],
    28: ['Materials', 'Ethics', 'Certifications', 'Communicate'],
    29: ['Team', 'Systems', 'Expand', 'Capital'],
    30: ['Localize', 'Global Markets', 'Future Tech', 'Legacy']
  },
  srs: {
    boxes: 5,
    intervals: [0, 1, 3, 7, 14],
    reviewBatchSize: 10
  },
  xp: {
    lessonComplete: 20,
    quizPerfect: 30,
    quizGood: 20,
    quizOk: 10,
    typingChallenge: 15,
    selfExplanation: 10,
    reviewCorrect: 5,
    mixedQuizComplete: 25
  },
  social: {
    hashtags: 'ClothingBusiness,FashionStartup,StartAClothingBrand,FashionEntrepreneur,ClothingLine2026',
    tweetTemplate: 'Just found this FREE Clothing Business Masterclass — {lessonCount} interactive lessons to start, brand & scale a clothing business! Templates, quizzes, and zero signup.'
  },
  branding: {
    trustStrip: 'We build production-grade web & mobile apps for fashion brands and e-commerce businesses. <strong>This free course is how we give back.</strong>',
    trustStripCta: 'Need an e-commerce app? Talk to us',
    headerSubtitle: 'From Idea to Fashion Empire — Free, Hands-On Clothing Business Training | by',
    ebookUrl: 'https://www.amazon.com/dp/B0GS3GSJ5V',
    ebookTitle: 'Get the Full Book',
    ebookSubtitle: 'Zero to Advanced Web Dev — the complete guide on Amazon',
    footerCtaTitle: 'Need a Custom E-commerce Platform for Your Brand?',
    footerCtaDesc: 'Teamz Lab builds production e-commerce platforms, mobile apps, and SaaS products with <strong style="color:var(--heading)">TypeScript, NestJS, React & Flutter</strong>. We built this free course — imagine what we can build for your fashion brand.',
    services: [
      { name: 'E-commerce Development', desc: 'Custom Shopify, WooCommerce, and headless commerce solutions for fashion brands' },
      { name: 'Mobile App Development', desc: 'Cross-platform Flutter & React Native shopping apps for iOS and Android' },
      { name: 'SaaS & Inventory Systems', desc: 'Custom inventory management, order tracking, and supply chain platforms' },
      { name: 'AI Integration & Consulting', desc: 'AI-powered size recommendations, trend forecasting, and customer personalization' }
    ]
  }
};
